ci:
  autoupdate_schedule: "quarterly"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '\.(pdb|gro|top|sdf)$'
  - id: debug-statements
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black-jupyter
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.8.5
  hooks:
    - id: nbqa-pyupgrade
      args:
        - --py38-plus
    - id: nbqa-isort
