ci:
  autoupdate_schedule: "quarterly"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '\.(pdb|gro|top|sdf)$'
  - id: debug-statements
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black-jupyter
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-pyupgrade
      files: ^examples
      args:
        - --py38-plus
    - id: nbqa-isort
      files: ^examples
