name: vignettes-env
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - python =3.10
  - openff-toolkit-base =0.13
  - openff-forcefields =2023.05
  - openff-interchange-base =0.3.3
  - openmm
  - ambertools
  - rdkit
  - mdtraj
  - panedr
  - nglview
  - ipywidgets ==7.7.1
